language: java
sudo: false
# see https://sormuras.github.io/blog/2018-03-20-jdk-matrix.html
matrix:
  include:
    # 8
    - env: JDK='OpenJDK 8'
      jdk: openjdk8
    # 11
    - env: JDK='OpenJDK 11'
      before_script: . $TRAVIS_BUILD_DIR/ci/install-jdk.sh -F 11 -L GPL
before_install:
  - jdk_switcher use openjdk8
  - git clone --depth 1 https://github.com/datastax/native-protocol.git
  - pushd native-protocol
  - mvn install -Dmaven.javadoc.skip=true -B -V
  - popd
  - rm -rf native-protocol
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -Djacoco.skip=true -B -V
cache:
  directories:
  - $HOME/.m2
