language: java
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
sudo: false
before_install: 
    # Require JDK8 for compiling
    - jdk_switcher use oraclejdk8
before_script:
    # Switch back to configured JDK for running tests
    - jdk_switcher use $TRAVIS_JDK_VERSION
cache:
  directories:
    - $HOME/.m2
